=== raid-codex/data/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "faction_slug": {
            "type": "string",
            "enum": [
                "banner-lords",
                "barbarians",
                "dark-elves",
                "demonspawn",
                "high-elves",
                "knight-revenant",
                "lizardmen",
                "ogryn-tribes",
                "orcs",
                "sacred-order",
                "skinwalker",
                "undead-hordes"
            ]
        },
        "faction_name": {
            "type": "string",
            "enum": [
                "Banner-Lords",
                "Barbarians",
                "Dark Elves",
                "Demonspawn",
                "High Elves",
                "Knight Revenant",
                "Lizardmen",
                "Ogryn-Tribes",
                "Orcs",
                "Sacred Order",
                "Skinwalker",
                "Undead Hordes"
            ]
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "$ref": "#/definitions/faction_name"
                },
                "slug": {
                    "$ref": "#/definitions/faction_slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [
                "raw_description",
                "effects"
            ],
            "properties": {
                "raw_description": {
                    "type": "string"
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "skill": {
            "type": "object",
            "required": [
                "raw_description",
                "slug",
                "name",
                "effects",
                "damaged_based_on"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "name": {
                    "type": "string"
                },
                "raw_description": {
                    "type": "string"
                },
                "damage_based_on": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "ATK",
                            "DEF",
                            "HP",
                            "SPD",
                            "Enemy MAX HP"
                        ]
                    }
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "status_effect": {
            "type": "object",
            "required": [
                "value",
                "type",
                "effect_type",
                "website_link",
                "image_slug",
                "slug"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "HP Burn",
                        "Poison",
                        "Decrease DEF",
                        "Decrease ACC",
                        "Decrease SPD",
                        "Decrease ATK",
                        "Weaken",
                        "Sleep",
                        "Provoke",
                        "Freeze",
                        "Block Cooldown Skills",
                        "Bomb",
                        "Stun",
                        "Block Buffs",
                        "Revive on Death",
                        "Heal Reduction",
                        "Leech",
                        "Debuff Spread",
                        "Increase C. RATE",
                        "Shield",
                        "Ally Protection",
                        "Reflect Damage",
                        "Increase DEF",
                        "Increase SPD",
                        "Increase ATK",
                        "Continuous Heal",
                        "Counterattack",
                        "Unkillable",
                        "Block Debuffs",
                        "Block Damage"
                    ]
                },
                "effect_type": {
                    "type": "string",
                    "enum": [
                        "buff",
                        "debuff"
                    ]
                }
            }
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^(<p>.+<\/p>)?$"
        }
    }
}

=== raid-codex/data/docs/champions/current/kael.json
{
  "name": "Kael",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Attack",
  "rating": {
    "overall": "A",
    "campaign": "A",
    "arena_offense": "A",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "S",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "A",
    "dragon": "B",
    "spider": "A",
    "fire_knight": "A",
    "minotaur": "A",
    "force_dungeon": "A",
    "magic_dungeon": "A",
    "spirit_dungeon": "A",
    "void_dungeon": "A"
  },
  "slug": "kael",
  "characteristics": {
    "60": {
      "hp": 13710,
      "attack": 1200,
      "defense": 914,
      "speed": 103,
      "critical_rate": 0.15,
      "critical_damage": 0.57,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally HP in all Battles by 15%.",
      "effects": []
    }
  ],
  "skills": [
    {
      "name": "Dark Bolt",
      "raw_description": "Attacks 1 enemy. Has an 80% chance of placing a 2.5% [Poison] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +10%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +10%<br>Lvl. 6 Damage +10%",
      "slug": "dark-bolt",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Poison",
          "value": 0,
          "image_slug": "image-debuff-poison-2",
          "slug": "poison-2",
          "website_link": "/debuff/poison",
          "extra": true
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Acid Rain",
      "raw_description": "Attacks all enemies. Has an extra 15% chance of inflicting a critical killed.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +5%",
      "slug": "acid-rain",
      "effects": [],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Disintegrate",
      "raw_description": "Attacks 4 times at random. Has a 40% chance of placing a 5% [Poison] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +10%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Cooldown -1",
      "slug": "disintegrate",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Poison",
          "value": 0,
          "image_slug": "image-debuff-poison-2",
          "slug": "poison-2",
          "website_link": "/debuff/poison",
          "extra": true
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    }
  ],
  "faction": {
    "name": "Dark Elves",
    "slug": "dark-elves",
    "website_link": "/factions/dark-elves/",
    "image_slug": "image-faction-dark-elves",
    "number_of_champions": 0,
    "default_description": "Dark Elves is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Dark Elves is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Dark Elves",
        "dark-elves"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "dark-elves",
  "website_link": "/champions/kael/",
  "image_slug": "image-champion-kael",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Kael is a rare attack champion from the faction Dark Elves doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Kael",
      "kael"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Dark Elves"
        },
        "description": "Member of the faction Dark Elves, Kael is a champion of Rare rarity and of Attack type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-kael.jpg",
        "name": "Kael",
        "url": "https://raid-codex.com/champions/kael/"
      }
    ]
  },
  "default_description": "Kael is a rare attack champion from the faction Dark Elves doing magic damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/data/docs/champions/current/warmaiden.json
{
  "name": "Warmaiden",
  "rarity": "Rare",
  "element": "Force",
  "type": "Attack",
  "rating": {
    "overall": "A",
    "campaign": "B",
    "arena_offense": "A",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "A",
    "clan_boss_with_giant_slayer": "B",
    "ice_guardian": "A",
    "dragon": "A",
    "spider": "B",
    "fire_knight": "C",
    "minotaur": "A",
    "force_dungeon": "A",
    "magic_dungeon": "C",
    "spirit_dungeon": "B",
    "void_dungeon": "B"
  },
  "slug": "warmaiden",
  "characteristics": {
    "60": {
      "hp": 14700,
      "attack": 1321,
      "defense": 727,
      "speed": 97,
      "critical_rate": 0.15,
      "critical_damage": 0.57,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Ferocious Attack",
      "raw_description": "Attacks 1 enemy. Has a 30% chance of placing a 2.5% [Poison] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Damage +10%<br>Lvl. 6 Damage +10%",
      "slug": "ferocious-attack",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Poison",
          "value": 0,
          "image_slug": "image-debuff-poison-2",
          "slug": "poison-2",
          "website_link": "/debuff/poison",
          "extra": true
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Opportunity Strike",
      "raw_description": "Attacks 1 enemy. Places a 50% [Increase ATK] buff on this Champion and places an extra hit if this attack is critical. The extra hit cannot be critical.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +5%",
      "slug": "opportunity-strike",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Increase ATK",
          "value": 0,
          "image_slug": "image-buff-increase-atk-2",
          "slug": "increase-atk-2",
          "website_link": "/buff/increase-atk",
          "extra": true
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Crumbling Blast",
      "raw_description": "Attacks all enemies. Has a 75% chance of placing a 60% [Decrease DEF] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +10%<br>Lvl. 3 Buff/Debuff Chance +10<br>Lvl. 4 Buff/Debuff Chance +159<br>Lvl. 5 Cooldown -1",
      "slug": "crumbling-blast",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Decrease DEF",
          "value": 0,
          "image_slug": "image-debuff-decrease-def-2",
          "slug": "decrease-def-2",
          "website_link": "/debuff/decrease-def",
          "extra": true
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    }
  ],
  "faction": {
    "name": "Barbarians",
    "slug": "barbarians",
    "website_link": "/factions/barbarians/",
    "image_slug": "image-faction-barbarians",
    "number_of_champions": 0,
    "default_description": "Barbarians is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Barbarians is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Barbarians",
        "barbarians"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "barbarians",
  "website_link": "/champions/warmaiden/",
  "image_slug": "image-champion-warmaiden",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Warmaiden is a rare attack champion from the faction Barbarians doing force damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Warmaiden",
      "warmaiden"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Barbarians"
        },
        "description": "Member of the faction Barbarians, Warmaiden is a champion of Rare rarity and of Attack type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-warmaiden.jpg",
        "name": "Warmaiden",
        "url": "https://raid-codex.com/champions/warmaiden/"
      }
    ]
  },
  "default_description": "Warmaiden is a rare attack champion from the faction Barbarians doing force damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/data/docs/champions/current/lemure.json
{
  "name": "Lemure",
  "rarity": "Uncommon",
  "element": "",
  "type": "HP",
  "rating": {
    "overall": "D",
    "campaign": "",
    "arena_offense": "",
    "arena_defense": "",
    "clan_boss_without_giant_slayer": "",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "",
    "dragon": "",
    "spider": "",
    "fire_knight": "",
    "minotaur": "",
    "force_dungeon": "",
    "magic_dungeon": "",
    "spirit_dungeon": "",
    "void_dungeon": ""
  },
  "slug": "lemure",
  "characteristics": {
    "60": {
      "hp": 18165,
      "attack": 639,
      "defense": 903,
      "speed": 93,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Vicious Swipes",
      "raw_description": "Attacks 1 enemy 2 times.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%",
      "slug": "vicious-swipes",
      "effects": [],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Dark Burst",
      "raw_description": "Attacks 1 enemy. Has a 60% chance of placing a [Bomb] that detonates in 3 turns.<br>Damage based on: [ATK] [HP]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +10%",
      "slug": "dark-burst",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Bomb",
          "value": 0,
          "image_slug": "image-debuff-bomb",
          "slug": "bomb",
          "website_link": "/debuffs/bomb",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": [
        "ATK",
        "HP"
      ]
    }
  ],
  "faction": {
    "name": "Demonspawn",
    "slug": "demonspawn",
    "website_link": "/factions/demonspawn/",
    "image_slug": "image-faction-demonspawn",
    "number_of_champions": 0,
    "default_description": "Demonspawn is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Demonspawn is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Demonspawn",
        "demonspawn"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "demonspawn",
  "website_link": "/champions/lemure/",
  "image_slug": "image-champion-lemure",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Lemure is a uncommon hp champion from the faction Demonspawn. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Lemure",
      "lemure"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Demonspawn"
        },
        "description": "Member of the faction Demonspawn, Lemure is a champion of Uncommon rarity and of HP type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-lemure.jpg",
        "name": "Lemure",
        "url": "https://raid-codex.com/champions/lemure/"
      }
    ]
  },
  "default_description": "Lemure is a uncommon hp champion from the faction Demonspawn",
  "recommended_builds": [],
  "lore": ""
}
