=== raid-codex/data/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "faction_slug": {
            "type": "string",
            "enum": [
                "banner-lords",
                "barbarians",
                "dark-elves",
                "demonspawn",
                "high-elves",
                "knight-revenant",
                "lizardmen",
                "ogryn-tribes",
                "orcs",
                "sacred-order",
                "skinwalker",
                "undead-hordes"
            ]
        },
        "faction_name": {
            "type": "string",
            "enum": [
                "Banner-Lords",
                "Barbarians",
                "Dark Elves",
                "Demonspawn",
                "High Elves",
                "Knight Revenant",
                "Lizardmen",
                "Ogryn-Tribes",
                "Orcs",
                "Sacred Order",
                "Skinwalker",
                "Undead Hordes"
            ]
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "$ref": "#/definitions/faction_name"
                },
                "slug": {
                    "$ref": "#/definitions/faction_slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [
                "raw_description",
                "effects"
            ],
            "properties": {
                "raw_description": {
                    "type": "string"
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "skill": {
            "type": "object",
            "required": [
                "raw_description",
                "slug",
                "name",
                "effects",
                "damaged_based_on"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "name": {
                    "type": "string"
                },
                "raw_description": {
                    "type": "string"
                },
                "damage_based_on": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "ATK",
                            "DEF",
                            "HP",
                            "SPD",
                            "Enemy MAX HP"
                        ]
                    }
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "status_effect": {
            "type": "object",
            "required": [
                "value",
                "type",
                "effect_type",
                "website_link",
                "image_slug",
                "slug"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "HP Burn",
                        "Poison",
                        "Decrease DEF",
                        "Decrease ACC",
                        "Decrease SPD",
                        "Decrease ATK",
                        "Weaken",
                        "Sleep",
                        "Provoke",
                        "Freeze",
                        "Block Cooldown Skills",
                        "Bomb",
                        "Stun",
                        "Block Buffs",
                        "Revive on Death",
                        "Heal Reduction",
                        "Leech",
                        "Debuff Spread",
                        "Increase C. RATE",
                        "Shield",
                        "Ally Protection",
                        "Reflect Damage",
                        "Increase DEF",
                        "Increase SPD",
                        "Increase ATK",
                        "Continuous Heal",
                        "Counterattack",
                        "Unkillable",
                        "Block Debuffs",
                        "Block Damage"
                    ]
                },
                "effect_type": {
                    "type": "string",
                    "enum": [
                        "buff",
                        "debuff"
                    ]
                }
            }
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^(<p>.+<\/p>)?$"
        }
    }
}

=== raid-codex/data/docs/champions/current/theurgist.json
{
  "name": "Theurgist",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Assist",
  "rating": {
    "overall": "B",
    "campaign": "C",
    "arena_offense": "B",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "theurgist",
  "characteristics": {
    "60": {
      "hp": 18495,
      "attack": 947,
      "defense": 848,
      "speed": 103,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Ice Debris",
      "raw_description": "Attacks 1 enemy. Fills the Turn Meter for a random ally by 10%.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +5%",
      "slug": "ice-debris",
      "effects": [],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Touch of Sealing",
      "raw_description": "Attacks 1 enemy. Has a 75% chance of placing a [Block Buffs] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Buff/Debuff Chance +15%<br>Lvl. 6 Cooldown -1 ane",
      "slug": "touch-of-sealing",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Block Buffs",
          "value": 0,
          "image_slug": "image-debuff-block-buffs",
          "slug": "block-buffs",
          "website_link": "/debuffs/block-buffs",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Uplift",
      "raw_description": "Places a 30% [Increase DEF] buff and a 25% [Increase ATK] buff on all allies for 2 turns.<br>Lvl. 2 Cooldown -1<br>Lvl. 3 Cooldown -1",
      "slug": "uplift",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Increase ATK",
          "value": 0,
          "image_slug": "image-buff-increase-atk",
          "slug": "increase-atk",
          "website_link": "/buffs/increase-atk",
          "extra": false,
          "raw_description": ""
        },
        {
          "effect_type": "buff",
          "type": "Increase DEF",
          "value": 0,
          "image_slug": "image-buff-increase-def",
          "slug": "increase-def",
          "website_link": "/buffs/increase-def",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": []
    }
  ],
  "faction": {
    "name": "Knight Revenant",
    "slug": "knight-revenant",
    "website_link": "/factions/knight-revenant/",
    "image_slug": "image-faction-knight-revenant",
    "number_of_champions": 0,
    "default_description": "Knight Revenant is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Knight Revenant is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Knight Revenant",
        "knight-revenant"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "knight-revenant",
  "website_link": "/champions/theurgist/",
  "image_slug": "image-champion-theurgist",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Theurgist is a rare assist champion from the faction Knight Revenant doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Theurgist",
      "theurgist"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Knight Revenant"
        },
        "description": "Member of the faction Knight Revenant, Theurgist is a champion of Rare rarity and of Assist type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-theurgist.jpg",
        "name": "Theurgist",
        "url": "https://raid-codex.com/champions/theurgist/"
      }
    ]
  },
  "default_description": "Theurgist is a rare assist champion from the faction Knight Revenant doing magic damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/data/docs/champions/current/hospitaller.json
{
  "name": "Hospitaller",
  "rarity": "Rare",
  "element": "Magic",
  "type": "Assist",
  "rating": {
    "overall": "B",
    "campaign": "B",
    "arena_offense": "A",
    "arena_defense": "B",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "C",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "B",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "B",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "hospitaller",
  "characteristics": {
    "60": {
      "hp": 17175,
      "attack": 1035,
      "defense": 848,
      "speed": 101,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally SPD in all Battles by 10%",
      "effects": []
    }
  ],
  "skills": [
    {
      "name": "Quick Slash",
      "raw_description": "Attacks 1 enemy.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5<br>Lvl. 3 Damage +5<br>Lvl. 4 Damage +10%",
      "slug": "quick-slash",
      "effects": [],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Wave of Purification",
      "raw_description": "Attacks all enemies. Has a 50% chance of removing 1 random buff from each target.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +10°<br>Lvl. 6 Damage +10%<br>Lvl. 7 Buff/Debuff Chance +109",
      "slug": "wave-of-purification",
      "effects": [],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Invigorating Prayers",
      "raw_description": "Places a 15% all allies for 2 turn",
      "slug": "invigorating-prayers",
      "effects": [],
      "damaged_based_on": []
    },
    {
      "name": "Merciful Partner",
      "raw_description": "Revives a random ally with 25% HP and places a [Block Damage] buff on them for 1 turn whenever H kills an enemy.",
      "slug": "merciful-partner",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Block Damage",
          "value": 0,
          "image_slug": "image-buff-block-damage",
          "slug": "block-damage",
          "website_link": "/buffs/block-damage",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": []
    }
  ],
  "faction": {
    "name": "Sacred Order",
    "slug": "sacred-order",
    "website_link": "/factions/sacred-order/",
    "image_slug": "image-faction-sacred-order",
    "number_of_champions": 0,
    "default_description": "Sacred Order is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Sacred Order is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Sacred Order",
        "sacred-order"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "sacred-order",
  "website_link": "/champions/hospitaller/",
  "image_slug": "image-champion-hospitaller",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Hospitaller is a rare assist champion from the faction Sacred Order doing magic damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Hospitaller",
      "hospitaller"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Sacred Order"
        },
        "description": "Member of the faction Sacred Order, Hospitaller is a champion of Rare rarity and of Assist type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-hospitaller.jpg",
        "name": "Hospitaller",
        "url": "https://raid-codex.com/champions/hospitaller/"
      }
    ]
  },
  "default_description": "Hospitaller is a rare assist champion from the faction Sacred Order doing magic damage",
  "recommended_builds": [],
  "lore": "<p>It is said that love often grows from compassion and mutual care, and, indeed, such is the case with Harrier and the Hospitaller. When he was wounded in battle, it was the young sister of the Hospitaller Order that saw to his wounds. Through the long recovery, they spoke to one another daily, pushing past the initial hurdles and becoming friends. Yet so was the ranger stricken by his saviour’s kindness and beauty, that he dared to seek her out even after recovering.</p><p>It was night when he arrived, sneaking through the window of the hospital in search of his flame. In hindsight, that was not a wise idea for his flame mistook the poor Harrier for a thief and knocked him out with a chair that happened to be nearby. Needless to say, the Hospitaller was less than pleased and he was subjected to quite a lecture - all while his new bruises were tended to.</p><p>Even so, despite unforeseen and rather blunt issues, the Harrier did manage to strike a chord in her heart. In time, the two started seeing one another in secret and their love blossomed, as it does still to this day. For there are no things more precious to Lumaya than two hearts united as one.</p>"
}

=== raid-codex/data/docs/champions/current/lugan-the-steadfast.json
{
  "name": "Lugan the Steadfast",
  "rarity": "Legendary",
  "element": "Spirit",
  "type": "HP",
  "rating": {
    "overall": "S",
    "campaign": "B",
    "arena_offense": "SS",
    "arena_defense": "SS",
    "clan_boss_without_giant_slayer": "S",
    "clan_boss_with_giant_slayer": "S",
    "ice_guardian": "S",
    "dragon": "S",
    "spider": "A",
    "fire_knight": "A",
    "minotaur": "S",
    "force_dungeon": "A",
    "magic_dungeon": "A",
    "spirit_dungeon": "A",
    "void_dungeon": "A"
  },
  "slug": "lugan-the-steadfast",
  "characteristics": {
    "60": {
      "hp": 20475,
      "attack": 925,
      "defense": 1013,
      "speed": 103,
      "critical_rate": 0.15,
      "critical_damage": 0.63,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Crushing Blow",
      "raw_description": "Attacks 1 enemy. Heals all allies except this Champion by 25% of the damage inflicted. Damage inflicted is proportional to MAX HP.<br>Damage based on: [HP]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Damage +10%",
      "slug": "crushing-blow",
      "effects": [],
      "damaged_based_on": [
        "HP"
      ]
    },
    {
      "name": "Bodyguard",
      "raw_description": "Places a 60% [Increase DEF] buff on this Champion for 3 turns. Also places a 50% [Ally Protection] buff on all allies for 2 turns. % Ally Protection<br>Lvl. 2 Cooldown -1",
      "slug": "bodyguard",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Ally Protection",
          "value": 0,
          "image_slug": "image-buff-ally-protection-2",
          "slug": "ally-protection",
          "website_link": "/buff/ally-protection",
          "extra": true
        },
        {
          "effect_type": "buff",
          "type": "Increase DEF",
          "value": 0,
          "image_slug": "image-buff-increase-def-2",
          "slug": "increase-def",
          "website_link": "/buff/increase-def",
          "extra": true
        }
      ],
      "damaged_based_on": []
    },
    {
      "name": "Mark of Silence",
      "raw_description": "Attacks all enemies. Has an 80% chance of placing a [Block Cooldown Skills] debuff for 2 turns.<br>Damage based on: [ATK]<br>Lvl. 2 Buff/Debuff Chance +5%<br>Lvl. 3 Damage +5%<br>Lvl. 4 Buff/Debuff Chance +5%<br>Lvl. 5 Damage +5%<br>Lvl. 6 Buff/Debuff Chance +10%<br>Lvl. 7 Damage +10%",
      "slug": "mark-of-silence",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Block Cooldown Skills",
          "value": 0,
          "image_slug": "image-debuff-block-cooldown-skills",
          "slug": "block-cooldown-skills",
          "website_link": "/debuff/block-cooldown-skills",
          "extra": false
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    }
  ],
  "faction": {
    "name": "Banner-Lords",
    "slug": "banner-lords",
    "website_link": "/factions/banner-lords/",
    "image_slug": "image-faction-banner-lords",
    "number_of_champions": 0,
    "default_description": "Banner-Lords is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Banner-Lords is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Banner-Lords",
        "banner-lords"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "banner-lords",
  "website_link": "/champions/lugan-the-steadfast/",
  "image_slug": "image-champion-lugan-the-steadfast",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Lugan the Steadfast is a legendary hp champion from the faction Banner-Lords doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Lugan the Steadfast",
      "lugan-the-steadfast"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Banner-Lords"
        },
        "description": "Member of the faction Banner-Lords, Lugan the Steadfast is a champion of Legendary rarity and of HP type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-lugan-the-steadfast.jpg",
        "name": "Lugan the Steadfast",
        "url": "https://raid-codex.com/champions/lugan-the-steadfast/"
      }
    ]
  },
  "default_description": "Lugan the Steadfast is a legendary hp champion from the faction Banner-Lords doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}
