=== raid-codex/data/schemas/champion.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "faction_slug": {
            "type": "string",
            "enum": [
                "banner-lords",
                "barbarians",
                "dark-elves",
                "demonspawn",
                "high-elves",
                "knight-revenant",
                "lizardmen",
                "ogryn-tribes",
                "orcs",
                "sacred-order",
                "skinwalker",
                "undead-hordes"
            ]
        },
        "faction_name": {
            "type": "string",
            "enum": [
                "Banner-Lords",
                "Barbarians",
                "Dark Elves",
                "Demonspawn",
                "High Elves",
                "Knight Revenant",
                "Lizardmen",
                "Ogryn-Tribes",
                "Orcs",
                "Sacred Order",
                "Skinwalker",
                "Undead Hordes"
            ]
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9\\-]+$"
        },
        "faction": {
            "type": "object",
            "required": [
                "name",
                "slug",
                "website_link",
                "image_slug",
                "number_of_champions",
                "default_description",
                "seo"
            ],
            "properties": {
                "name": {
                    "$ref": "#/definitions/faction_name"
                },
                "slug": {
                    "$ref": "#/definitions/faction_slug"
                },
                "website_link": {
                    "type": "string"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "number_of_champions": {
                    "type": "integer"
                },
                "default_description": {
                    "type": "string"
                },
                "seo": {
                    "$ref": "#/definitions/seo"
                }
            }
        },
        "aura": {
            "type": "object",
            "required": [
                "raw_description",
                "effects"
            ],
            "properties": {
                "raw_description": {
                    "type": "string"
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "skill": {
            "type": "object",
            "required": [
                "raw_description",
                "slug",
                "name",
                "effects",
                "damaged_based_on"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "name": {
                    "type": "string"
                },
                "raw_description": {
                    "type": "string"
                },
                "damage_based_on": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "ATK",
                            "DEF",
                            "HP",
                            "SPD",
                            "Enemy MAX HP"
                        ]
                    }
                },
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/status_effect"
                    }
                }
            }
        },
        "status_effect": {
            "type": "object",
            "required": [
                "value",
                "type",
                "effect_type",
                "website_link",
                "image_slug",
                "slug"
            ],
            "properties": {
                "slug": {
                    "$ref": "#/definitions/slug"
                },
                "image_slug": {
                    "$ref": "#/definitions/slug"
                },
                "website_link": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "HP Burn",
                        "Poison",
                        "Decrease DEF",
                        "Decrease ACC",
                        "Decrease SPD",
                        "Decrease ATK",
                        "Weaken",
                        "Sleep",
                        "Provoke",
                        "Freeze",
                        "Block Cooldown Skills",
                        "Bomb",
                        "Stun",
                        "Block Buffs",
                        "Revive on Death",
                        "Heal Reduction",
                        "Leech",
                        "Debuff Spread",
                        "Increase C. RATE",
                        "Shield",
                        "Ally Protection",
                        "Reflect Damage",
                        "Increase DEF",
                        "Increase SPD",
                        "Increase ATK",
                        "Continuous Heal",
                        "Counterattack",
                        "Unkillable",
                        "Block Debuffs",
                        "Block Damage"
                    ]
                },
                "effect_type": {
                    "type": "string",
                    "enum": [
                        "buff",
                        "debuff"
                    ]
                }
            }
        },
        "seo": {
            "type": "object",
            "required": [
                "title",
                "description",
                "keywords"
            ],
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "characteristics": {
            "type": "object",
            "required": [
                "hp",
                "attack",
                "defense",
                "speed",
                "critical_rate",
                "critical_damage",
                "resistance",
                "accuracy"
            ],
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "critical_rate": {
                    "type": "number"
                },
                "critical_damage": {
                    "type": "number"
                },
                "resistance": {
                    "type": "integer"
                },
                "accuracy": {
                    "type": "integer"
                }
            }
        },
        "rating_value": {
            "type": "string",
            "enum": [
                "",
                "D",
                "C",
                "B",
                "A",
                "S",
                "SS"
            ]
        },
        "rating": {
            "type": "object",
            "required": [],
            "properties": {
                "overall": {
                    "$ref": "#/definitions/rating_value"
                },
                "campaign": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_offense": {
                    "$ref": "#/definitions/rating_value"
                },
                "arena_defense": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_without_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "clan_boss_with_giant_slayer": {
                    "$ref": "#/definitions/rating_value"
                },
                "ice_guardian": {
                    "$ref": "#/definitions/rating_value"
                },
                "dragon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spider": {
                    "$ref": "#/definitions/rating_value"
                },
                "fire_knight": {
                    "$ref": "#/definitions/rating_value"
                },
                "minotaur": {
                    "$ref": "#/definitions/rating_value"
                },
                "force_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "magic_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "spirit_dungeon": {
                    "$ref": "#/definitions/rating_value"
                },
                "void_dungeon": {
                    "$ref": "#/definitions/rating_value"
                }
            }
        },
        "build": {
            "type": "object",
            "required": [],
            "properties": {}
        }
    },
    "type": "object",
    "required": [
        "name",
        "rarity",
        "element",
        "type",
        "rating",
        "slug",
        "characteristics",
        "auras",
        "skills",
        "faction",
        "faction_slug",
        "website_link",
        "image_slug",
        "seo",
        "default_description",
        "recommended_builds"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "string",
            "enum": [
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary"
            ]
        },
        "element": {
            "type": "string",
            "enum": [
                "Magic",
                "Force",
                "Void",
                "Spirit",
                ""
            ]
        },
        "type": {
            "type": "string",
            "enum": [
                "HP",
                "Attack",
                "Assist",
                "Def",
                ""
            ]
        },
        "rating": {
            "$ref": "#/definitions/rating"
        },
        "slug": {
            "$ref": "#/definitions/slug"
        },
        "characteristics": {
            "type": "object",
            "required": [
                "60"
            ],
            "properties": {
                "60": {
                    "$ref": "#/definitions/characteristics"
                }
            }
        },
        "auras": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/aura"
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/skill"
            }
        },
        "faction": {
            "$ref": "#/definitions/faction"
        },
        "faction_slug": {
            "$ref": "#/definitions/slug"
        },
        "website_link": {
            "type": "string"
        },
        "image_slug": {
            "$ref": "#/definitions/slug"
        },
        "seo": {
            "$ref": "#/definitions/seo"
        },
        "default_description": {
            "type": "string"
        },
        "recommended_builds": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/build"
            }
        },
        "lore": {
            "type": "string",
            "pattern": "^(<p>.+<\/p>)?$"
        }
    }
}

=== raid-codex/data/docs/champions/current/zelotah.json
{
  "name": "Zelotah",
  "rarity": "Epic",
  "element": "Spirit",
  "type": "Assist",
  "rating": {
    "overall": "A",
    "campaign": "A",
    "arena_offense": "A",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "A",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "A",
    "dragon": "A",
    "spider": "A",
    "fire_knight": "A",
    "minotaur": "A",
    "force_dungeon": "A",
    "magic_dungeon": "A",
    "spirit_dungeon": "A",
    "void_dungeon": "A"
  },
  "slug": "zelotah",
  "characteristics": {
    "60": {
      "hp": 20640,
      "attack": 826,
      "defense": 1101,
      "speed": 95,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 30,
      "accuracy": 15
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally RESIST in the Arena by 70.<br> of hy,",
      "effects": []
    }
  ],
  "skills": [
    {
      "name": "Hypnotic Gaze",
      "raw_description": "Attacks 1 enemy. Has a 15% chance of placing a [Sleep] debuff for 1 turn.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +10%<br>Lvl. 6 Buff/Debuff Chance +10% Ios. ‘a ™ Y, ‘",
      "slug": "hypnotic-gaze",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Sleep",
          "value": 0,
          "image_slug": "image-debuff-sleep",
          "slug": "sleep",
          "website_link": "/debuff/sleep",
          "extra": false
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    },
    {
      "name": "Armored Scales",
      "raw_description": "Places a [Shield] buff on all allies equal to 20% of this Champion's MAX HP for 3 turns. Places a 15% [Continuous Heal] buff on all allies for 2 turns.<br>Lvl. 2 Shield +5%<br>Lvl. 3 Shield +5%<br>Lvl. 4 Shield +5%<br>Lvl. 5 Shield +5%",
      "slug": "armored-scales",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Continuous Heal",
          "value": 0,
          "image_slug": "image-buff-continuous-heal-2",
          "slug": "continuous-heal-2",
          "website_link": "/buff/continuous-heal",
          "extra": true
        },
        {
          "effect_type": "buff",
          "type": "Shield",
          "value": 0,
          "image_slug": "image-buff-shield",
          "slug": "shield",
          "website_link": "/buff/shield",
          "extra": false
        }
      ],
      "damaged_based_on": []
    },
    {
      "name": "Horrid Dreams",
      "raw_description": "Attacks all enemies. Has a 50% chance of placing a [Sleep] debuff for 1 turn. Has a 75% chance against enemies under debuffs.<br>Damage based on: [ATK]<br>Lvl. 2 Damage +10%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Buff/Debuff Chance +10%<br>Lvl. 5 Buff/Debuff Chance +10%<br>Lvl. 6 Cooldown -1",
      "slug": "horrid-dreams",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Sleep",
          "value": 0,
          "image_slug": "image-debuff-sleep",
          "slug": "sleep",
          "website_link": "/debuff/sleep",
          "extra": false
        }
      ],
      "damaged_based_on": [
        "ATK"
      ]
    }
  ],
  "faction": {
    "name": "Undead Hordes",
    "slug": "undead-hordes",
    "website_link": "/factions/undead-hordes/",
    "image_slug": "image-faction-undead-hordes",
    "number_of_champions": 0,
    "default_description": "Undead Hordes is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Undead Hordes is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Undead Hordes",
        "undead-hordes"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "undead-hordes",
  "website_link": "/champions/zelotah/",
  "image_slug": "image-champion-zelotah",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Zelotah is a epic assist champion from the faction Undead Hordes doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Zelotah",
      "zelotah"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Undead Hordes"
        },
        "description": "Member of the faction Undead Hordes, Zelotah is a champion of Epic rarity and of Assist type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-zelotah.jpg",
        "name": "Zelotah",
        "url": "https://raid-codex.com/champions/zelotah/"
      }
    ]
  },
  "default_description": "Zelotah is a epic assist champion from the faction Undead Hordes doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}

=== raid-codex/data/docs/champions/current/seducer.json
{
  "name": "Seducer",
  "rarity": "Rare",
  "element": "Void",
  "type": "Def",
  "rating": {
    "overall": "B",
    "campaign": "C",
    "arena_offense": "A",
    "arena_defense": "S",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "C",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "C",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "seducer",
  "characteristics": {
    "60": {
      "hp": 16185,
      "attack": 628,
      "defense": 1321,
      "speed": 95,
      "critical_rate": 0.15,
      "critical_damage": 0.5,
      "resistance": 40,
      "accuracy": 0
    }
  },
  "auras": [
    {
      "raw_description": "Increases Ally HP in all Battles by 25%.",
      "effects": []
    }
  ],
  "skills": [
    {
      "name": "Lulling Touch",
      "raw_description": "Attacks 1 enemy. Has a 30% chance of placing a [Sleep] debuff for 1 turn.<br>Damage based on: [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +10%<br>Lvl. 6 Damage +10%",
      "slug": "lulling-touch",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Sleep",
          "value": 0,
          "image_slug": "image-debuff-sleep",
          "slug": "sleep",
          "website_link": "/debuff/sleep",
          "extra": false
        }
      ],
      "damaged_based_on": [
        "DEF"
      ]
    },
    {
      "name": "Disorienting Blast",
      "raw_description": "Attacks all enemies. Has a 75% chance of placing a 25% [Decrease ATK] debuff for 2 turns.<br>Damage based on: [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +10%<br>Lvl. 4 Damage +10%<br>Lvl. 5 Buff/Debuff Chance +15%",
      "slug": "disorienting-blast",
      "effects": [
        {
          "effect_type": "debuff",
          "type": "Decrease ATK",
          "value": 0,
          "image_slug": "image-debuff-decrease-atk",
          "slug": "decrease-atk",
          "website_link": "/debuff/decrease-atk",
          "extra": false
        }
      ],
      "damaged_based_on": [
        "DEF"
      ]
    },
    {
      "name": "Twisted Devotion",
      "raw_description": "Places a 30% [Increase DEF] buff on all allies for 2 turns and a [Block Debuffs] buff on all allies for 2 turns.<br>Lvl. 2 Cooldown -1",
      "slug": "twisted-devotion",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Block Debuffs",
          "value": 0,
          "image_slug": "image-buff-block-debuffs",
          "slug": "block-debuffs",
          "website_link": "/buff/block-debuffs",
          "extra": false
        },
        {
          "effect_type": "buff",
          "type": "Increase DEF",
          "value": 0,
          "image_slug": "image-buff-increase-def",
          "slug": "increase-def",
          "website_link": "/buff/increase-def",
          "extra": false
        }
      ],
      "damaged_based_on": []
    },
    {
      "name": "Selfless Partner",
      "raw_description": "Places a 50% [Ally Protection] buff on all allies for 2 turns. Places a {Block Damage] buff on this Champion for 1 turn.<br>Lvl. 2 Cooldown -1",
      "slug": "selfless-partner",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Ally Protection",
          "value": 0,
          "image_slug": "image-buff-ally-protection-2",
          "slug": "ally-protection-2",
          "website_link": "/buff/ally-protection",
          "extra": true
        }
      ],
      "damaged_based_on": []
    }
  ],
  "faction": {
    "name": "Undead Hordes",
    "slug": "undead-hordes",
    "website_link": "/factions/undead-hordes/",
    "image_slug": "image-faction-undead-hordes",
    "number_of_champions": 0,
    "default_description": "Undead Hordes is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Undead Hordes is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Undead Hordes",
        "undead-hordes"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "undead-hordes",
  "website_link": "/champions/seducer/",
  "image_slug": "image-champion-seducer",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Seducer is a rare def champion from the faction Undead Hordes doing void damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Seducer",
      "seducer"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Undead Hordes"
        },
        "description": "Member of the faction Undead Hordes, Seducer is a champion of Rare rarity and of Def type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-seducer.jpg",
        "name": "Seducer",
        "url": "https://raid-codex.com/champions/seducer/"
      }
    ]
  },
  "default_description": "Seducer is a rare def champion from the faction Undead Hordes doing void damage",
  "recommended_builds": [],
  "lore": "<p>Where Lumaya brings us the purity of love, Siroth places his bets on the pure carnal desire. He tempts with excess and indulgence, pulling more and more willing servants into his net wherever he can. Such was the fate of a young noble of Kaerok, vain and greedy, he wished for nothing more than to better his position in power and lot in life. By the magic of Siroth’s necromancers, and by his own dark deeds he was granted a vampire’s “kiss”, turning into one of the undead beasts himself. But his pact with the Shadow stood firm, for the noble was allowed to retain his humanly looks that he so adored - for a time, at least.</p><p>One can only imagine this wicked Seducer’s shock and surprise when he was faced with another servant of Siroth, known as the Temptress. A child of a vampire and a mortal woman, she was as vain and self-assured as he was himself. And throughout all his attempts to gain the upper hand, the Seducer only succeeded in catching himself in his own trap. For even the darkest heart can sometimes be illuminated by Lumaya’s light, and he found himself hopelessly in love and at the whims of the woman he sought to outdo.</p><p>Still, it may not be such a horrible fate in the end, for despite their mutual viciousness and less than savoury practices, the two of them do go together as well as a werewolf and a full moon. That connection is hard to deny, and it overcomes even the deeply ingrained selfishness that both of them were so known for.</p>"
}

=== raid-codex/data/docs/champions/current/metalshaper.json
{
  "name": "Metalshaper",
  "rarity": "Rare",
  "element": "Spirit",
  "type": "Assist",
  "rating": {
    "overall": "B",
    "campaign": "B",
    "arena_offense": "B",
    "arena_defense": "A",
    "clan_boss_without_giant_slayer": "C",
    "clan_boss_with_giant_slayer": "C",
    "ice_guardian": "B",
    "dragon": "B",
    "spider": "D",
    "fire_knight": "C",
    "minotaur": "B",
    "force_dungeon": "C",
    "magic_dungeon": "B",
    "spirit_dungeon": "C",
    "void_dungeon": "B"
  },
  "slug": "metalshaper",
  "characteristics": {
    "60": {
      "hp": 16350,
      "attack": 859,
      "defense": 1079,
      "speed": 90,
      "critical_rate": 0.15,
      "critical_damage": 0.57,
      "resistance": 30,
      "accuracy": 0
    }
  },
  "auras": [],
  "skills": [
    {
      "name": "Transference Bolt",
      "raw_description": "Attacks 1 enemy. Has a 30% chance of stealing 1 random buff from the target.<br>Damage based on: [DEF]<br>Lvl. 2 Damage +5%<br>Lvl. 3 Buff/Debuff Chance +5%<br>Lvl. 4 Damage +5%<br>Lvl. 5 Buff/Debuff Chance +5%<br>Lvl. 6 Damage +5%<br>Lvl. 7 Buff/Debuff Chance +5%",
      "slug": "transference-bolt",
      "effects": [],
      "damaged_based_on": [
        "DEF"
      ]
    },
    {
      "name": "Fortified Steel",
      "raw_description": "Places a [Shield] buff on all allies for 2 turns. The value of [Shield] is proportional to this Champion Level.<br>Lvl. 2 Shield +5%<br>Lvl. 3 Shield +5%<br>Lvl. 4 Shield +10%<br>Lvl. 5 Cooldown -1",
      "slug": "fortified-steel",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Shield",
          "value": 0,
          "image_slug": "image-buff-shield",
          "slug": "shield",
          "website_link": "/buffs/shield",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": []
    },
    {
      "name": "Rescue",
      "raw_description": "Removes all debuffs from an ally with the lowest HP, then heals this ally by 20% of this Champion MAX HP. Places a 25% [Increase DEF] buff on the target for 3 turns.<br>Lvl. 2 Heal +10%<br>Lvl. 3 Heal +10%<br>Lvl. 4 Cooldown -1",
      "slug": "rescue",
      "effects": [
        {
          "effect_type": "buff",
          "type": "Increase DEF",
          "value": 0,
          "image_slug": "image-buff-increase-def",
          "slug": "increase-def",
          "website_link": "/buffs/increase-def",
          "extra": false,
          "raw_description": ""
        }
      ],
      "damaged_based_on": []
    }
  ],
  "faction": {
    "name": "Lizardmen",
    "slug": "lizardmen",
    "website_link": "/factions/lizardmen/",
    "image_slug": "image-faction-lizardmen",
    "number_of_champions": 0,
    "default_description": "Lizardmen is a faction from RAID Shadow Legends",
    "seo": {
      "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
      "description": "Lizardmen is a faction from RAID Shadow Legends. Find out more on this Raid Shadow Legends codex.",
      "keywords": [
        "raid",
        "shadow",
        "legends",
        "factions",
        "Lizardmen",
        "lizardmen"
      ],
      "structured_data": null
    }
  },
  "faction_slug": "lizardmen",
  "website_link": "/champions/metalshaper/",
  "image_slug": "image-champion-metalshaper",
  "seo": {
    "title": "%%title%% %%page%% %%sep%% %%parent_title%% %%sep%% %%sitename%%",
    "description": "Metalshaper is a rare assist champion from the faction Lizardmen doing spirit damage. Find out more on this Raid Shadow Legends codex.",
    "keywords": [
      "raid",
      "shadow",
      "legends",
      "champions",
      "tier",
      "list",
      "Metalshaper",
      "metalshaper"
    ],
    "structured_data": [
      {
        "@context": "http://schema.org/",
        "@type": "Person",
        "affiliation": {
          "@context": "http://schema.org",
          "@type": "Organization",
          "name": "Lizardmen"
        },
        "description": "Member of the faction Lizardmen, Metalshaper is a champion of Rare rarity and of Assist type",
        "image": "https://raid-codex.com/wp-content/uploads/champions/image-champion-metalshaper.jpg",
        "name": "Metalshaper",
        "url": "https://raid-codex.com/champions/metalshaper/"
      }
    ]
  },
  "default_description": "Metalshaper is a rare assist champion from the faction Lizardmen doing spirit damage",
  "recommended_builds": [],
  "lore": ""
}
